version: '3'
services:
  explore-redis:
    privileged: true
    image: redis:latest
    restart: always
    volumes:
      - ./redis/data:/data:rw
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass 123456"]