version: '3.8'
networks:
   orbiter-network:
    external: true
    labels:
      - "com.docker.compose.project=orbiter-explore"
services:
  refinery:
    image: orbiter/explore-data-refinery:latest
    labels:
      - "com.docker.compose.project=orbiter-explore"
    build:
      context: ./
      cache_from:
        - orbiter/clients
      dockerfile:  ./apps/explore-DataRefinery/Dockerfile.clients
    restart: always
    environment:
      CONSUL_URL: '${CONSUL_URL}'
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
    networks:
      - orbiter-network
    volumes:
      - './runtime/refinery:/app/runtime'
      - './logs/refinery:/app/logs'
