version: '3.8'
networks:
   orbiter-network:
    external: true
services:
  metrics:
    image: orbiter/metrics:latest
    build:
      context: ./
      cache_from:
        - orbiter/clients
      dockerfile:  ./apps/metrics/Dockerfile
    restart: always
    command: ["node", 'main.js']
    ports:
      - '3002:3000'
    networks:
      - orbiter-network
    volumes:
      - './runtime/metrics:/app/runtime'
      - './logs/metrics:/app/logs'
