version: '3.8'
networks:
   orbiter-network:
    external: true
services:
  dataSync:
    image: orbiter/data-synchronization:latest
    build:
      context: ./
      cache_from:
        - orbiter/clients
      dockerfile:  ./apps/data-synchronization/Dockerfile.clients
    restart: always
    command: ["node", 'main.js']
    environment:
      CONSUL_URL: '${CONSUL_URL}'
    ports:
      - '3222:3007'
    networks:
      - orbiter-network
    volumes:
      - './runtime/dataSync:/app/runtime'
      - './logs/dataSync:/app/logs'
      - './sqls:/app/sqls'
