version: '3.8'
networks:
   orbiter-network:
    external: true
    labels:
      - "com.docker.compose.project=openapi"
services:
  sdk-api:
    container_name: "sdk-api"
    image: orbiter/sdk-api:latest
    labels:
      - "com.docker.compose.project=sdk-api"
    build:
      context: ./
      cache_from:
        - orbiter/clients
      dockerfile:  ./apps/openapi/Dockerfile
    restart: always
    env_file: .env
    ports:
      - '9005:3000'
    networks:
      - orbiter-network
    volumes:
      - './runtime:/app/runtime'
      - './logs:/app/logs'
