version: '3.8'
networks:
   orbiter-network:
    external: true
    labels:
      - "com.docker.compose.project=orbiter-explore"
services:
  crawler2:
    image: orbiter/explore-data-crawler:latest
    labels:
      - "com.docker.compose.project=orbiter-explore"
    build:
      context: ./
      cache_from:
        - orbiter/clients
      dockerfile:  ./apps/explore-DataCrawler/Dockerfile.clients
    restart: always
    command: ["node", 'main.js']
    env_file: .env
    ports:
      - ':3000'
    networks:
      - orbiter-network
    volumes:
      - './runtime/crawler:/app/runtime'
      - './logs/crawler:/app/logs'
