version: '3.5'

services:

  # Cluster Logs Shipper ------------------------------
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    restart: always
    # -e flag to log to stderr and disable syslog/file output
    command: -e --strict.perms=false
    user: root
    environment:
      LOGSTASH_HOST: 192.168.1.29:5044
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: changeme
      KIBANA_HOST_PORT: 192.168.1.29:5601
      ELASTICSEARCH_HOST_PORT: https://192.168.1.29:9200
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /Users/kakui/projects/client-monorepo/logs:/var/log:ro