version: '3.5'

services:

  # Cluster Logs Shipper ------------------------------
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.2
    restart: always
    # -e flag to log to stderr and disable syslog/file output
    command: -e --strict.perms=false
    user: root
    environment:
      LOGSTASH_HOST: ""
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /Users/kakui/projects/client-monorepo/logs:/var/log:ro