version: '3'
services:
  postgres:
    image: bitnami/postgresql:15.4.0
    container_name: my-postgres
    restart: always
    environment:
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRESQL_POSTGRES_PASSWORD}
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES: pgaudit,pg_stat_statements
    ports:
      - "5433:5432"
    volumes:
      - './data:/bitnami/postgresql'
      # - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: