version: '3.8'
networks:
  app-network:
    driver: bridge
services:
  assets:
    image: nginx:stable-alpine
    container_name: assets
    ports:
      - 80:80
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - './static:/static'
    networks:
      - app-network
