version: '3'
services:
  rabbitmq:
    image: bitnami/rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_DISK_FREE_RELATIVE_LIMIT: 0.5
    volumes:
        - ./rabbit:/bitnami
      # - ./rabbitmq_data:/bitnami/rabbitmq/data
      # - ./rabbitmq_conf:/opt/bitnami/rabbitmq/etc/rabbitmq

volumes:
  rabbitmq_data:
  rabbitmq_conf:
