version: '3.8'
networks:
  app-network:
    driver: bridge
services:
  explore-DataRefinery:
    image: orbiter/explore-data-refinery:latest
    restart: always
    environment:
      CONSUL_URL: '${CONSUL_URL}'
    networks:
      - app-network
    volumes:
      - './runtime:/app/runtime'
      - './logs:/app/logs'