version: '3.8'
networks:
  app-network:
    driver: bridge
services:
  explore-DataRefinery:
    image: orbiter/explore-data-refinery:latest
    restart: always
    environment:
      CONSUL_HOST: '${CONSUL_HOST}'
      CONSUL_PORT: '${CONSUL_PORT}'
      CONSUL_TOKEN: '${CONSUL_TOKEN}'
    networks:
      - app-network
    volumes:
      - './runtime:/app/runtime'
      - './logs:/app/logs'